name: airbnb-nextjs-springboot

on:
  push:
    branches:
      - master
      - main
    paths:
      - "backend/**"
      - "frontend/**"

env:
  PROJECT_ID: ${{ secrets.CLOUD_RUN_PROJECT_NAME }}
  REGION: europe-north1
  REPO_NAME_BACKEND: airbnb-nextjs-springboot-backend
  REPO_NAME_FRONTEND: airbnb-nextjs-springboot-frontend

jobs:
  build-and-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Authenticate with Google Cloud
      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.CLOUD_RUN_SERVICE_ACCOUNT }}"

      # Setup gcloud CLI/SDK
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Authorize Docker push
        run: gcloud auth configure-docker

      - name: Build and tag the backend docker image
        working-directory: ./backend
        run: |
          docker build --build-arg MONGODB_PASSWORD=${{ secrets.MONGODB_PASSWORD }} --build-arg GITHUB_CLIENT_ID=${{ secrets.GH_CLIENT_ID }} --build-arg GITHUB_CLIENT_SECRET=${{ secrets.GH_CLIENT_SECRET }} --build-arg DEFAULT_SUCCESS_URL=${{ secrets.DEFAULT_SUCCESS_URL }} --tag gcr.io/$PROJECT_ID/$REPO_NAME_BACKEND:$GITHUB_SHA .

      - name: Build and tag the frontend docker image
        working-directory: ./frontend
        run: |
          docker build --tag gcr.io/$PROJECT_ID/$REPO_NAME_FRONTEND:$GITHUB_SHA .

      - name: Push the backend image to the Google Container Registry (GCR)
        run: |
          docker push gcr.io/$PROJECT_ID/$REPO_NAME_BACKEND:$GITHUB_SHA

      - name: Push the frontend image to the Google Container Registry (GCR)
        run: |
          docker push gcr.io/$PROJECT_ID/$REPO_NAME_FRONTEND:$GITHUB_SHA

      - name: Deploy backend
        run: |
          gcloud run deploy $REPO_NAME_BACKEND \
            --region $REGION \
            --image gcr.io/$PROJECT_ID/$REPO_NAME_BACKEND:$GITHUB_SHA \
            --platform "managed" \
            --quiet

      - name: Deploy frontend
        run: |
          gcloud run deploy $REPO_NAME_FRONTEND \
            --region $REGION \
            --image gcr.io/$PROJECT_ID/$REPO_NAME_FRONTEND:$GITHUB_SHA \
            --platform "managed" \
            --quiet
